# Generated by Django 5.0.1 on 2024-02-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('image', models.ImageField(blank=True, upload_to='images/produits/', verbose_name='image')),
                ('qr_code', models.ImageField(blank=True, upload_to='images/qr_code', verbose_name='QR code')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', related_query_name='produit', to='App.categorie', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='quantity')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('total', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='total')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', related_query_name='ligne_facture', to='App.facture', verbose_name='invoice')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', related_query_name='ligne_facture', to='App.produit', verbose_name='product')),
            ],
            options={
                'verbose_name': 'invoice line',
                'verbose_name_plural': 'invoice lines',
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie', 'nom'], name='App_produit_categor_361c72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lignefacture',
            unique_together={('produit', 'facture')},
        ),
    ]
