# Generated by Django 5.0.1 on 2024-03-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_categorie_facture_produit_lignefacture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'verbose_name': 'LigneFacture', 'verbose_name_plural': 'LigneFactures'},
        ),
    ]
